[package]
name = "domain"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
diesel = { version = "2.2.6", features = ["postgres"] }
serde = { version = "1.0.217", features = ["derive"] }