[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
domain = { path = "../domain" }

rocket = { version = "0.5.1", features = ["json"] }
serde = { version = "1.0.217", features = ["derive"] }